'use strict';

// Shared mutable state between server.js and handler modules.
// server.js populates this at init time, handlers read/write through it.

const state = {
  // Mutable state variables
  page: null,
  browser: null,
  browserSessionId: 0,
  consoleLogs: [],
  networkLogs: [],
  pageErrors: [],
  currentCheckpoint: new Date().toISOString(),
  lastAction: null,
  eventCheckpoint: new Date().toISOString(),
  sessions: new Map(),
  activeSessionName: 'default',
  sessionCounter: 0,
  traceLogs: [],
  traceActive: false,
  currentTraceName: null,
  backendProbeResults: [],
  instrumentationEnabled: false,
  imageErrors: [],
  lastImageErrorCheckpoint: new Date().toISOString(),
  validationResults: [],
  lastQualityChecks: { visual: [], a11y: null, performance: null },
  lastValidationRun: null,
  requestStartTimes: new Map(),

  // Functions (set by server.js after they're defined)
  ensurePage: null,
  text: null,
  log: null,
  resetRuntimeLogs: null,
  getPageLinks: null,
  postActionErrorCheck: null,
  probeKnownEndpoints: null,
  getUnifiedErrors: null,
  closeBrowserSession: null,
  listBrowserSessions: null,
  filterNetwork: null,
  filterNetworkDetails: null,
  getStorageSnapshot: null,
  buildDebugReport: null,
  captureStepEvidence: null,
  waitForCondition: null,
  assertPage: null,
  runFlow: null,
  installInstrumentation: null,
  getBrowserEvents: null,
  clearBrowserEvents: null,
  startTrace: null,
  stopTrace: null,
  getArtifacts: null,
  clearArtifacts: null,
  ensureArtifactsDir: null,
  screenshotWithRedaction: null,
  safeArtifactName: null,
  analyzeScreenshotForErrors: null,
  exportHar: null,
  runFullAudit: null,
  visualBaseline: null,
  visualCompare: null,
  visualReport: null,
  runA11yCheck: null,
  runPerformanceCheck: null,
  runLighthouseAudit: null,
  findElement: null, 
  findPage: null,
  suggestLocator: null,
  validateLocator: null,
  mcpHealthCheck: null,
  projectAudit: null,
  mcpSelfTest: null,
  runValidationCheck: null,
  runValidationPlan: null,
  runValidationElement: null,
  runValidationFlow: null,
  buildValidationReport: null,
  exportValidationReport: null,
  runValidationQuickRun: null,
  runDeployVerify: null,
  investigateDebug: null,
  runBrowserFullRegression: null,
  traverseMenu: null,
  fetchBackendLogs: null,
  buildTraceChain: null,
  detectSilentFailures: null,
  redact: null,
  
  // Constants
  MAX_SESSIONS: 2,
  SCREENSHOT_DIR: null,
  HAR_DIR: null,
  VISUAL_DIR: null,
  VISUAL_BASELINE_DIR: null,
  VISUAL_ACTUAL_DIR: null,
  VISUAL_DIFF_DIR: null,

  // Modules
  browserOperator: null,
  evidenceCollector: null,
  deepInteractor: null,
  errorAggregator: null,
};

module.exports = state;
